
const moment = require('./moment.js')


var bankinfo=[
    {
        "id":"101q7hutv885j",
        "rate":"A+",
        "short_name":"茌平农商行"
    },
    {
        "id":"10m1j75hsw5oe",
        "rate":"A",
        "short_name":"汶上农商行"
    },
    {
        "id":"10m2y34v2iiof",
        "rate":"A",
        "short_name":"梁山农商行"
    },
    {
        "id":"10m4wn1b594og",
        "rate":"A",
        "short_name":"垦利农商行"
    },
    {
        "id":"10vufg7pdsv6p",
        "rate":"A+",
        "short_name":"曹县农商行"
    },
    {
        "id":"1187mu0on7vpl",
        "rate":"AA+",
        "short_name":"宁夏银行"
    },
    {
        "id":"11pnokbva9w8n",
        "rate":"A",
        "short_name":"登封农商行"
    },
    {
        "id":"11ppac9qfab8o",
        "rate":"A+",
        "short_name":"西平农商行"
    },
    {
        "id":"11pqqbwz07p8p",
        "rate":"A+",
        "short_name":"临桂农商行"
    },
    {
        "id":"128v6z2uu6q60",
        "rate":"AA",
        "short_name":"富阳农商行"
    },
    {
        "id":"12dcuy8tejkrd",
        "rate":"AA-",
        "short_name":"贵阳农商行"
    },
    {
        "id":"130jfq2o82eo0",
        "rate":"A+",
        "short_name":"临猗农商行"
    },
    {
        "id":"130lqvqci8lo1",
        "rate":"AA-",
        "short_name":"建湖农商行"
    },
    {
        "id":"136mn7h9cgb7n",
        "rate":"A",
        "short_name":"奉化农商行"
    },
    {
        "id":"136o3gkewch7o",
        "rate":"AA-",
        "short_name":"莱芜农商行"
    },
    {
        "id":"13w9jmas1y0i4",
        "rate":"AA",
        "short_name":"唐山农商行"
    },
    {
        "id":"13wbc5vm478i5",
        "rate":"A",
        "short_name":"苍山农信社"
    },
    {
        "id":"143w24k0o9kfr",
        "rate":"A+",
        "short_name":"官渡农合行"
    },
    {
        "id":"143xlh4saqefs",
        "rate":"A",
        "short_name":"蓬溪农信社"
    },
    {
        "id":"148w5htl20rma",
        "rate":"A+",
        "short_name":"乌当农商行"
    },
    {
        "id":"14s8r9ad9uq43",
        "rate":"AA-",
        "short_name":"沭阳农商行"
    },
    {
        "id":"14saks85pje44",
        "rate":"AA-",
        "short_name":"高邮农商行"
    },
    {
        "id":"14vf5hra6atmc",
        "rate":"A",
        "short_name":"永泰农信社"
    },
    {
        "id":"151vdbl5h98pn",
        "rate":"A",
        "short_name":"温岭村镇行"
    },
    {
        "id":"152d2fjqz184b",
        "rate":"AA-",
        "short_name":"菏泽农商行"
    },
    {
        "id":"152evmb9kk34c",
        "rate":"A+",
        "short_name":"漓江农合行"
    },
    {
        "id":"152gwhuoh4z4d",
        "rate":"AA-",
        "short_name":"南宁农信社"
    },
    {
        "id":"154vndrkgygpw",
        "rate":"A+",
        "short_name":"怀远农商行"
    },
    {
        "id":"154xf2x8pbupx",
        "rate":"A",
        "short_name":"射洪农商行"
    },
    {
        "id":"155zdff21ibe",
        "rate":"A+",
        "short_name":"永济农商行"
    },
    {
        "id":"1563mepbowrpt",
        "rate":"AA-",
        "short_name":"颍淮农商行"
    },
    {
        "id":"1585vpoemvbf",
        "rate":"A",
        "short_name":"垣曲农商行"
    },
    {
        "id":"15tfwww0zel9a",
        "rate":"A+",
        "short_name":"珲春农商行"
    },
    {
        "id":"15tiawdqvbb9b",
        "rate":"A",
        "short_name":"红山农信社"
    },
    {
        "id":"15tjnej90g99c",
        "rate":"A",
        "short_name":"长顺农信社"
    },
    {
        "id":"16jqwb0bk0ka3",
        "rate":"A-",
        "short_name":"松山农商行"
    },
    {
        "id":"16kgez8uvmk2s",
        "rate":"A-",
        "short_name":"包头农商行"
    },
    {
        "id":"16kgjbplagfrj",
        "rate":"A+",
        "short_name":"邕宁农信社"
    },
    {
        "id":"16ki6q0fif42v",
        "rate":"A+",
        "short_name":"淮海农商行"
    },
    {
        "id":"16uhwr5eb0k8j",
        "rate":"A+",
        "short_name":"遂州农信社"
    },
    {
        "id":"18f3hgdazni8r",
        "rate":"AA",
        "short_name":"大丰农商行"
    },
    {
        "id":"18txvm8r4nq5u",
        "rate":"A+",
        "short_name":"武义农商行"
    },
    {
        "id":"18u254mrd9e5v",
        "rate":"A+",
        "short_name":"邳州农商行"
    },
    {
        "id":"193sh7n6sgang",
        "rate":"AAA",
        "short_name":"昆仑银行"
    },
    {
        "id":"193tay74vmhnh",
        "rate":"AA",
        "short_name":"天山农商行"
    },
    {
        "id":"19a7qnih2sra1",
        "rate":"A-",
        "short_name":"固镇农商行"
    },
    {
        "id":"19eef4mw9qra2",
        "rate":"A+",
        "short_name":"成武农商行"
    },
    {
        "id":"19fdkaq2de7a3",
        "rate":"A",
        "short_name":"乐至农信社"
    },
    {
        "id":"19uupimkz67ir",
        "rate":"AA",
        "short_name":"泰安银行"
    },
    {
        "id":"19v9b4kvbg9iz",
        "rate":"A+",
        "short_name":"泗洪农商行"
    },
    {
        "id":"19w2pe99s3nlf",
        "rate":"AA-",
        "short_name":"苍南农商行"
    },
    {
        "id":"1a0sz9r2685fr",
        "rate":"A",
        "short_name":"龙里农商行"
    },
    {
        "id":"1aae3amwm4x6o",
        "rate":"A+",
        "short_name":"皖东农商行"
    },
    {
        "id":"1alcc0diqga8m",
        "rate":"A+",
        "short_name":"宝应农商行"
    },
    {
        "id":"1auk7ujhfm56r",
        "rate":"AA-",
        "short_name":"黑河农商行"
    },
    {
        "id":"1ax0ueuscy5mg",
        "rate":"AA-",
        "short_name":"龙湾农商银行"
    },
    {
        "id":"1azvc5vd3lk9q",
        "rate":"A",
        "short_name":"龙马潭农商行"
    },
    {
        "id":"1b3eu1nfg15h9",
        "rate":"AA-",
        "short_name":"桐乡农商行"
    },
    {
        "id":"1bbksneybw6a3",
        "rate":"A+",
        "short_name":"溧水农商行"
    },
    {
        "id":"1bo5f339z8gqe",
        "rate":"AA-",
        "short_name":"长江商行"
    },
    {
        "id":"1bpaapgth6g5c",
        "rate":"A",
        "short_name":"汤阴农商行"
    },
    {
        "id":"1e4iop8u8urao",
        "rate":"A+",
        "short_name":"定海海洋农商行"
    },
    {
        "id":"1f31qp4m2vsit",
        "rate":"A+",
        "short_name":"桐城农商行"
    },
    {
        "id":"1f6g0eftmkn3b",
        "rate":"A",
        "short_name":"通化农商行"
    },
    {
        "id":"1f6iarh362a3c",
        "rate":"A",
        "short_name":"太商村镇行"
    },
    {
        "id":"1f6jvr1ugek3d",
        "rate":"AA-",
        "short_name":"眉山农商行"
    },
    {
        "id":"1f6l4gjpmzr3e",
        "rate":"A",
        "short_name":"青神农商行"
    },
    {
        "id":"1hn1j6fuyru4d",
        "rate":"A",
        "short_name":"霍邱农商行"
    },
    {
        "id":"1igad3yzdzzi2",
        "rate":"A+",
        "short_name":"龙游农商行"
    },
    {
        "id":"1iim3lfk2jdi7",
        "rate":"AA-",
        "short_name":"寿光农商行"
    },
    {
        "id":"1iiwyj2oht2i8",
        "rate":"AA",
        "short_name":"长春农商行"
    },
    {
        "id":"1ij4jvs2rusqj",
        "rate":"A+",
        "short_name":"什邡农信社"
    },
    {
        "id":"1jf8pncqp1h8u",
        "rate":"BBB",
        "short_name":"尤溪成功村镇行"
    },
    {
        "id":"1jfa3utq8478v",
        "rate":"A+",
        "short_name":"萧县农商行"
    },
    {
        "id":"1lp3cp5fzkkk7",
        "rate":"AAA",
        "short_name":"邮储银行"
    },
    {
        "id":"1mecuiz7zv6n0",
        "rate":"A+",
        "short_name":"榆树农商行"
    },
    {
        "id":"1mhu5ekf90o84",
        "rate":"AAA",
        "short_name":"顺德农商行"
    },
    {
        "id":"1mhumwolfmu85",
        "rate":"AAA",
        "short_name":"江南农商行"
    },
    {
        "id":"1ncfezkslpwj6",
        "rate":"AAA",
        "short_name":"汇丰银行"
    },
    {
        "id":"1ndt3ah6hb3kq",
        "rate":"AA+",
        "short_name":"稠州商行"
    },
    {
        "id":"1opjhhl31opig",
        "rate":"AA-",
        "short_name":"莒县农商行"
    },
    {
        "id":"1opmgqn7nqlbz",
        "rate":"AA",
        "short_name":"湖州银行"
    },
    {
        "id":"1p1spd1bs3h",
        "rate":"AA-",
        "short_name":"龙口农商行"
    },
    {
        "id":"1q66wtkuzbf54",
        "rate":"AA+",
        "short_name":"江阴农商行"
    },
    {
        "id":"1qayi7a38k5m",
        "rate":"A-",
        "short_name":"泗县农商行"
    },
    {
        "id":"1qdxn7gajtbav",
        "rate":"AA-",
        "short_name":"长春发展农商行"
    },
    {
        "id":"1r1frras4zbk",
        "rate":"A+",
        "short_name":"阳谷农商行"
    },
    {
        "id":"1r9tejvri0b6b",
        "rate":"A",
        "short_name":"灌云农商行"
    },
    {
        "id":"1r9y482hb6x6c",
        "rate":"A",
        "short_name":"杨凌农商行"
    },
    {
        "id":"1tnv0j66l8u5v",
        "rate":"AA+",
        "short_name":"华兴银行"
    },
    {
        "id":"1uo2h9kduaan1",
        "rate":"AA-",
        "short_name":"遂宁商行"
    },
    {
        "id":"1v02jfrxi40pm",
        "rate":"AA+",
        "short_name":"绍兴银行"
    },
    {
        "id":"1v5mqyecauwq6",
        "rate":"A+",
        "short_name":"清镇农商行"
    },
    {
        "id":"1vfrthymcnm6h",
        "rate":"AA-",
        "short_name":"福州农商行"
    },
    {
        "id":"1wt63p56pxxmj",
        "rate":"BBB",
        "short_name":"稠州村镇行"
    },
    {
        "id":"1wuyeb7tl85a",
        "rate":"AA-",
        "short_name":"南浔农商行"
    },
    {
        "id":"1wxisur0zmbmu",
        "rate":"A+",
        "short_name":"修文农信社"
    },
    {
        "id":"1wzfjy85cmxhc",
        "rate":"A",
        "short_name":"曲阜农商行"
    },
    {
        "id":"1xgvx5ohiziiw",
        "rate":"AA-",
        "short_name":"莱州农商行"
    },
    {
        "id":"1xyrpxij0fflz",
        "rate":"A",
        "short_name":"陵城农商行"
    },
    {
        "id":"1yrdn4j3yx9cj",
        "rate":"AA",
        "short_name":"廊坊银行"
    },
    {
        "id":"1zio321meqvot",
        "rate":"A+",
        "short_name":"单县农商行"
    },
    {
        "id":"20clani6nqeg7",
        "rate":"A+",
        "short_name":"东至农商行"
    },
    {
        "id":"21y8mr45h1p2w",
        "rate":"A+",
        "short_name":"博兴农商行"
    },
    {
        "id":"224pcouigswro",
        "rate":"A+",
        "short_name":"太和农商行"
    },
    {
        "id":"23d9238xal6mt",
        "rate":"A+",
        "short_name":"诸城农商行"
    },
    {
        "id":"248ngqgkfhmi5",
        "rate":"AA",
        "short_name":"新郑农商行"
    },
    {
        "id":"24h9ia1d5ewhv",
        "rate":"A",
        "short_name":"井冈山农商行"
    },
    {
        "id":"265npb59ud7bt",
        "rate":"A",
        "short_name":"曲沃农商行"
    },
    {
        "id":"26f0eqknyckne",
        "rate":"AA-",
        "short_name":"西宁农商行"
    },
    {
        "id":"27o24dsuhfxh8",
        "rate":"AA-",
        "short_name":"济源农商行"
    },
    {
        "id":"27uwsap5c6vlv",
        "rate":"A",
        "short_name":"绛县农商行"
    },
    {
        "id":"291s76vk8t4bz",
        "rate":"AA-",
        "short_name":"铜山农商行"
    },
    {
        "id":"29dbdbms9e4qz",
        "rate":"AA-",
        "short_name":"郑州市郊联社"
    },
    {
        "id":"29yg6rmwjoch1",
        "rate":"AA-",
        "short_name":"汇和银行"
    },
    {
        "id":"2asq0im40iqnw",
        "rate":"A-",
        "short_name":"商河农商行"
    },
    {
        "id":"2bwse68ugoel3",
        "rate":"A",
        "short_name":"江阳农商行"
    },
    {
        "id":"2c8g3zmsmxu5h",
        "rate":"AA-",
        "short_name":"哈密商行"
    },
    {
        "id":"2cbz7quekygjt",
        "rate":"A+",
        "short_name":"滑县农商行"
    },
    {
        "id":"2cyrcbml99qnp",
        "rate":"A-",
        "short_name":"桦甸农商行"
    },
    {
        "id":"2cysxaf1nwdnq",
        "rate":"BBB+",
        "short_name":"修武农商行"
    },
    {
        "id":"2dweps3kz3e",
        "rate":"AA",
        "short_name":"嘉兴银行"
    },
    {
        "id":"2f2owem5svrp6",
        "rate":"AA",
        "short_name":"青海银行"
    },
    {
        "id":"2f2v3z3tjwib7",
        "rate":"BBB+",
        "short_name":"义乌村镇行"
    },
    {
        "id":"2fw0l9um25kr7",
        "rate":"A-",
        "short_name":"灌南农商行"
    },
    {
        "id":"2fw13ix3fzlr8",
        "rate":"A+",
        "short_name":"敦化农商行"
    },
    {
        "id":"2g7gmy6tgege",
        "rate":"AA",
        "short_name":"金谷农商行"
    },
    {
        "id":"2g8ds6doitgf",
        "rate":"AA-",
        "short_name":"乌海银行"
    },
    {
        "id":"2gb7o7owwugh",
        "rate":"AA",
        "short_name":"鄂尔多斯银行"
    },
    {
        "id":"2grtxvj8xj4gf",
        "rate":"AA-",
        "short_name":"长兴农商行"
    },
    {
        "id":"2grz0cu4t6ogg",
        "rate":"AA-",
        "short_name":"莆田农商行"
    },
    {
        "id":"2i2hw14qigs3j",
        "rate":"A",
        "short_name":"太平农商行"
    },
    {
        "id":"2ibp81dgk7u7l",
        "rate":"A+",
        "short_name":"安溪农信社"
    },
    {
        "id":"2ion2hjr54mlt",
        "rate":"A",
        "short_name":"介休农商行"
    },
    {
        "id":"2j7ickuif1slx",
        "rate":"AA+",
        "short_name":"珠海华润银行"
    },
    {
        "id":"2l0p0ywaehg9u",
        "rate":"A",
        "short_name":"渑池农商行"
    },
    {
        "id":"2l0qub6p01e9w",
        "rate":"A",
        "short_name":"上栗农商行"
    },
    {
        "id":"2l91lnny1r0kp",
        "rate":"AA-",
        "short_name":"融和农商行"
    },
    {
        "id":"2loi2hz7gx8bj",
        "rate":"A+",
        "short_name":"东营农商行"
    },
    {
        "id":"2lwfy1nmd3a98",
        "rate":"A+",
        "short_name":"德化农信社"
    },
    {
        "id":"2mqom6pb2pwq0",
        "rate":"AA",
        "short_name":"洛阳农商行"
    },
    {
        "id":"2nckwc9dincqm",
        "rate":"A+",
        "short_name":"歙县农商行"
    },
    {
        "id":"2nfc7j5mn1ko0",
        "rate":"AA",
        "short_name":"义乌农商行"
    },
    {
        "id":"2nl9nldjnvs9d",
        "rate":"A",
        "short_name":"龙门农商行"
    },
    {
        "id":"2p2inin7oo5y",
        "rate":"AA",
        "short_name":"九台农商行"
    },
    {
        "id":"2qe8t3dxriiqx",
        "rate":"A+",
        "short_name":"衢江农商行"
    },
    {
        "id":"2qz7eectcr446",
        "rate":"A+",
        "short_name":"龙岩农商行"
    },
    {
        "id":"2qzoskmxrf63",
        "rate":"AA-",
        "short_name":"余姚农合行"
    },
    {
        "id":"2rbuuxrez7m5g",
        "rate":"AA",
        "short_name":"抚顺银行"
    },
    {
        "id":"2rbvpokgew65h",
        "rate":"AA-",
        "short_name":"烟台农商行"
    },
    {
        "id":"2rl1kc826944w",
        "rate":"A+",
        "short_name":"颍泉农商行"
    },
    {
        "id":"2rl2e6oh7w04x",
        "rate":"A+",
        "short_name":"文登农商行"
    },
    {
        "id":"2ru450hokpu4r",
        "rate":"A+",
        "short_name":"双阳农商行"
    },
    {
        "id":"2s4944bs318kl",
        "rate":"AA-",
        "short_name":"伊川农商行"
    },
    {
        "id":"2s49ppb4qsckm",
        "rate":"A+",
        "short_name":"茅台农商行"
    },
    {
        "id":"2tkflk0nl5kgq",
        "rate":"A+",
        "short_name":"闽侯农信社"
    },
    {
        "id":"2uuurb92achv",
        "rate":"A+",
        "short_name":"海盐农商行"
    },
    {
        "id":"2uy3ut4f3wkcm",
        "rate":"A+",
        "short_name":"成泰农商行"
    },
    {
        "id":"2v8wo98p47gcu",
        "rate":"AA",
        "short_name":"通商银行"
    },
    {
        "id":"2wj12q6fpa29s",
        "rate":"A+",
        "short_name":"青田农商行"
    },
    {
        "id":"2wj2obtmpki9t",
        "rate":"A",
        "short_name":"乡宁农商行"
    },
    {
        "id":"2wszd0bcuiy8v",
        "rate":"AAA",
        "short_name":"三菱东京银行"
    },
    {
        "id":"2wx1eok4w1oa1",
        "rate":"AAA",
        "short_name":"东莞农商行"
    },
    {
        "id":"2wyqg6iivg4ag",
        "rate":"A",
        "short_name":"襄垣农商行"
    },
    {
        "id":"2xt0jjv65ew74",
        "rate":"A+",
        "short_name":"鄄城农商行"
    },
    {
        "id":"2y9rsbdgh30pg",
        "rate":"AA",
        "short_name":"济南农商行"
    },
    {
        "id":"2ynl4k24k3ipc",
        "rate":"BBB",
        "short_name":"润丰村镇行"
    },
    {
        "id":"2yoeh7dytq8pd",
        "rate":"BBB-",
        "short_name":"上虞富民村镇银行"
    },
    {
        "id":"2z19adz178kq6",
        "rate":"AAA",
        "short_name":"德意志银行"
    },
    {
        "id":"304vovmcm74id",
        "rate":"AA",
        "short_name":"珠海农商行"
    },
    {
        "id":"30cdo8o9i1yej",
        "rate":"AA+",
        "short_name":"南海农商行"
    },
    {
        "id":"321s1s4njfgdr",
        "rate":"AA-",
        "short_name":"永嘉农村行"
    },
    {
        "id":"321uk8f5vteds",
        "rate":"AA-",
        "short_name":"长治银行"
    },
    {
        "id":"321wntz9ai6dt",
        "rate":"A+",
        "short_name":"宁阳农商行"
    },
    {
        "id":"32ey9g9ifugj5",
        "rate":"A-",
        "short_name":"交行上海分行"
    },
    {
        "id":"33bgv6sxc6imw",
        "rate":"AA-",
        "short_name":"星展银行上海分行"
    },
    {
        "id":"357x4u2tzuccp",
        "rate":"AA",
        "short_name":"遂宁银行"
    },
    {
        "id":"357xrgizx2acq",
        "rate":"A",
        "short_name":"金乡农商行"
    },
    {
        "id":"35sfak3c6n0ba",
        "rate":"AA+",
        "short_name":"苏州银行"
    },
    {
        "id":"363fkuuuny269",
        "rate":"A+",
        "short_name":"花溪农商行"
    },
    {
        "id":"37dh0jiavca4h",
        "rate":"A",
        "short_name":"苍溪农商行"
    },
    {
        "id":"38m80ace68w2s",
        "rate":"AA-",
        "short_name":"路桥农合行"
    },
    {
        "id":"38mame65a702t",
        "rate":"A+",
        "short_name":"象山农信联社"
    },
    {
        "id":"39blifuvogir6",
        "rate":"AA-",
        "short_name":"哈尔滨农商行"
    },
    {
        "id":"39pyy44tz6omb",
        "rate":"A",
        "short_name":"灵石农商行"
    },
    {
        "id":"39pzw4k9jramc",
        "rate":"A+",
        "short_name":"安庆农商行"
    },
    {
        "id":"3a1j4dgi18y34",
        "rate":"A+",
        "short_name":"侯马农商行"
    },
    {
        "id":"3b0ab5zxv0442",
        "rate":"AA-",
        "short_name":"延边农商行"
    },
    {
        "id":"3bapbm4qyoyhg",
        "rate":"AA-",
        "short_name":"安丘农商行"
    },
    {
        "id":"3byk8ygjcsopz",
        "rate":"AA-",
        "short_name":"东阳农商行"
    },
    {
        "id":"3bynrw3usc2q2",
        "rate":"AA",
        "short_name":"诸暨农商行"
    },
    {
        "id":"3c9fa3m5ewk63",
        "rate":"A+",
        "short_name":"五台农商行"
    },
    {
        "id":"3dblcv8a0yi5l",
        "rate":"AAA",
        "short_name":"民生银行上海自贸分行"
    },
    {
        "id":"3ehy56k6gt24z",
        "rate":"AA-",
        "short_name":"临海农商行"
    },
    {
        "id":"3ei1oyq21em50",
        "rate":"AA-",
        "short_name":"潍坊农商行"
    },
    {
        "id":"3ei4akbkv8g51",
        "rate":"AA-",
        "short_name":"永康农商行"
    },
    {
        "id":"3erwft7tjyofs",
        "rate":"A+",
        "short_name":"呈贡区联社"
    },
    {
        "id":"3et34t9hq7c2s",
        "rate":"AA-",
        "short_name":"安吉农商行"
    },
    {
        "id":"3et4s9euqgk2t",
        "rate":"AA",
        "short_name":"晋城银行"
    },
    {
        "id":"3et733n1wue2u",
        "rate":"A",
        "short_name":"三门农商行"
    },
    {
        "id":"3gp60ycisaoke",
        "rate":"AA-",
        "short_name":"威海农商行"
    },
    {
        "id":"3gp8vvlcbikkf",
        "rate":"AA-",
        "short_name":"郓城农商行"
    },
    {
        "id":"3hymypvvloqfa",
        "rate":"A-",
        "short_name":"金湖农商行"
    },
    {
        "id":"3hyntp6jagwfb",
        "rate":"A",
        "short_name":"赤壁农商银行"
    },
    {
        "id":"3i4i5u3e1feiz",
        "rate":"A",
        "short_name":"隆昌农商行"
    },
    {
        "id":"3irbmyl1ils2s",
        "rate":"AA-",
        "short_name":"兰山农商行"
    },
    {
        "id":"3iremxn1z3y2t",
        "rate":"A+",
        "short_name":"德州农商行"
    },
    {
        "id":"3jjaizd01tg7g",
        "rate":"A",
        "short_name":"常山农信社"
    },
    {
        "id":"3jn895lcz483a",
        "rate":"AA+",
        "short_name":"张家港农商行"
    },
    {
        "id":"3jt2x418y9opr",
        "rate":"AA-",
        "short_name":"德州银行"
    },
    {
        "id":"3jt5jeeg6p2pu",
        "rate":"A+",
        "short_name":"玉环农商行"
    },
    {
        "id":"3jt81jg3qvwpv",
        "rate":"A+",
        "short_name":"椒江农合行"
    },
    {
        "id":"3jtgzfcvch8pw",
        "rate":"AA",
        "short_name":"承德银行"
    },
    {
        "id":"3jtw0a0b4p4py",
        "rate":"A+",
        "short_name":"黄岩农合行"
    },
    {
        "id":"3jtyi9o2lawpz",
        "rate":"A+",
        "short_name":"费县农商行"
    },
    {
        "id":"3ju1ngt42heq0",
        "rate":"AA-",
        "short_name":"德清农商行"
    },
    {
        "id":"3jww6bm2imwr6",
        "rate":"A+",
        "short_name":"磐安农商行"
    },
    {
        "id":"3kiedp3vy2s",
        "rate":"AA+",
        "short_name":"无锡农商行"
    },
    {
        "id":"3kqtjfbsu8u9p",
        "rate":"A+",
        "short_name":"柯城农商行"
    },
    {
        "id":"3l7m3gpnpsmcp",
        "rate":"A+",
        "short_name":"醴陵农商行"
    },
    {
        "id":"3lypdazm9viv",
        "rate":"A+",
        "short_name":"新昌农商行"
    },
    {
        "id":"3mfytxa403uae",
        "rate":"A+",
        "short_name":"大兴安岭农商行"
    },
    {
        "id":"3n9w01yitsufs",
        "rate":"A",
        "short_name":"简阳农商行"
    },
    {
        "id":"3nwwwzn661yl2",
        "rate":"A",
        "short_name":"慈利农商行"
    },
    {
        "id":"3q9u8nlkg5acf",
        "rate":"AA-",
        "short_name":"嵊州农商行"
    },
    {
        "id":"3qabw6qbaq0cm",
        "rate":"AAA",
        "short_name":"兴业银行上海分行"
    },
    {
        "id":"3qoliqs2abufl",
        "rate":"AA-",
        "short_name":"清远农商行"
    },
    {
        "id":"3rk3w9i8pmw61",
        "rate":"A+",
        "short_name":"巩义农商行"
    },
    {
        "id":"3se5mlzl8zai1",
        "rate":"A",
        "short_name":"长兴村镇行"
    },
    {
        "id":"3t63sppzgpy5d",
        "rate":"A+",
        "short_name":"禹城农商行"
    },
    {
        "id":"3tv4euou7tubq",
        "rate":"AA+",
        "short_name":"吴江农商行"
    },
    {
        "id":"3tvuscll97ucf",
        "rate":"AA-",
        "short_name":"长兴农合行"
    },
    {
        "id":"3tw0az19viecg",
        "rate":"A",
        "short_name":"红塔农合行"
    },
    {
        "id":"3u31598394egw",
        "rate":"A+",
        "short_name":"郯城农商行"
    },
    {
        "id":"3utsnf1m51shz",
        "rate":"AA",
        "short_name":"太仓农商行"
    },
    {
        "id":"3w6e8h7zv4cpe",
        "rate":"A",
        "short_name":"新沂农商行"
    },
    {
        "id":"3xcczo26j78jd",
        "rate":"A+",
        "short_name":"济宁农商行"
    },
    {
        "id":"3xjhcd67mw4fz",
        "rate":"A+",
        "short_name":"定远农商行"
    },
    {
        "id":"3xxwhwdewemjf",
        "rate":"A",
        "short_name":"长子农商行"
    },
    {
        "id":"3yqamarxnv0gm",
        "rate":"AA+",
        "short_name":"威海商行"
    },
    {
        "id":"3z08i64pa9c6c",
        "rate":"AA",
        "short_name":"红塔商行"
    },
    {
        "id":"3zjqz3hdv9sne",
        "rate":"AA",
        "short_name":"临商银行"
    },
    {
        "id":"40vrra4d75eir",
        "rate":"A+",
        "short_name":"宜兴农商行"
    },
    {
        "id":"41bmr32kx44ka",
        "rate":"BBB+",
        "short_name":"鼎湖农信社"
    },
    {
        "id":"42lqmxbxctshu",
        "rate":"A+",
        "short_name":"运城农商行"
    },
    {
        "id":"42lvzgpjqdmhv",
        "rate":"AA",
        "short_name":"海宁农商行"
    },
    {
        "id":"42n279ujv9289",
        "rate":"A",
        "short_name":"五河农商行"
    },
    {
        "id":"4323zey2wpejx",
        "rate":"AA-",
        "short_name":"宁波市区农信社"
    },
    {
        "id":"433t03r50x0l8",
        "rate":"AA-",
        "short_name":"鄂三峡农商行"
    },
    {
        "id":"438yozl47jw91",
        "rate":"A",
        "short_name":"兖州农商行"
    },
    {
        "id":"43ucpkqz8so2u",
        "rate":"AA",
        "short_name":"秦农农商行"
    },
    {
        "id":"44ivihtpmwa6t",
        "rate":"AA-",
        "short_name":"荣成农商行"
    },
    {
        "id":"45rwfhemsgqj8",
        "rate":"AA-",
        "short_name":"宜宾商行"
    },
    {
        "id":"45zuqa3hjw4b",
        "rate":"A",
        "short_name":"河津农商行"
    },
    {
        "id":"461wyipey24e",
        "rate":"AA-",
        "short_name":"姜堰农商行"
    },
    {
        "id":"465e2wxuov4h",
        "rate":"AA",
        "short_name":"上虞农商行"
    },
    {
        "id":"4686orf6904i",
        "rate":"AA-",
        "short_name":"泰州农商行"
    },
    {
        "id":"46a3pthbzd4j",
        "rate":"A",
        "short_name":"涟水农商行"
    },
    {
        "id":"46o1r0xrjnaml",
        "rate":"A",
        "short_name":"攀枝花农商行"
    },
    {
        "id":"46orrra2cv4k",
        "rate":"A",
        "short_name":"泰顺农信社"
    },
    {
        "id":"46ux3nv8sqao2",
        "rate":"AA+",
        "short_name":"昆山农商行"
    },
    {
        "id":"48hkgaczgzokp",
        "rate":"A",
        "short_name":"文成农信社"
    },
    {
        "id":"48zobb7yvr2lj",
        "rate":"A",
        "short_name":"汪清农商行"
    },
    {
        "id":"49683k09ldull",
        "rate":"A-",
        "short_name":"怀集农信社"
    },
    {
        "id":"4aziffzzgm4j2",
        "rate":"A+",
        "short_name":"邢台农商行"
    },
    {
        "id":"4clwqjbf8oie",
        "rate":"AA",
        "short_name":"海安农商行"
    },
    {
        "id":"4eb1ia2t84amy",
        "rate":"A+",
        "short_name":"天台农商行"
    },
    {
        "id":"4es55i8loja7o",
        "rate":"A+",
        "short_name":"衡水农商行"
    },
    {
        "id":"4fmx2aijkb0e2",
        "rate":"AA",
        "short_name":"海南银行"
    },
    {
        "id":"4gtsst8ach3s",
        "rate":"A+",
        "short_name":"利辛农商行"
    },
    {
        "id":"4gzgywndck3t",
        "rate":"A-",
        "short_name":"罗源农信社"
    },
    {
        "id":"4hbowtnwpn4a",
        "rate":"A+",
        "short_name":"昌吉农商行"
    },
    {
        "id":"4hsoymixnna63",
        "rate":"AA-",
        "short_name":"平阳农商行"
    },
    {
        "id":"4ht03uxyf7264",
        "rate":"AA",
        "short_name":"华瑞银行"
    },
    {
        "id":"4ht5vxglah265",
        "rate":"AAA",
        "short_name":"光大银行上海分行"
    },
    {
        "id":"4jb32fit0depi",
        "rate":"AA-",
        "short_name":"晋中开发农商行"
    },
    {
        "id":"4ju6uwvjuugeg",
        "rate":"A+",
        "short_name":"齐河农商行"
    },
    {
        "id":"4jz4i4urjxc4o",
        "rate":"A1",
        "short_name":"汇丰银行上海分行"
    },
    {
        "id":"4k42095sbfw63",
        "rate":"AA",
        "short_name":"余姚农商行"
    },
    {
        "id":"4kfvuavbyfubm",
        "rate":"A-",
        "short_name":"崇义农商行"
    },
    {
        "id":"4koen0v9x7gu",
        "rate":"AA-",
        "short_name":"温州民商银行"
    },
    {
        "id":"4kotugutpa26d",
        "rate":"AA",
        "short_name":"自贡银行"
    },
    {
        "id":"4kvx6py6u84hq",
        "rate":"A+",
        "short_name":"淮北农商行"
    },
    {
        "id":"4lb5gia9a8c4l",
        "rate":"A-",
        "short_name":"洪雅联社"
    },
    {
        "id":"4llvisyrzf8if",
        "rate":"AA",
        "short_name":"达州商行"
    },
    {
        "id":"4lmojpiijcuih",
        "rate":"AA+",
        "short_name":"唐山银行"
    },
    {
        "id":"4ls05cz9z8k6c",
        "rate":"A+",
        "short_name":"凉山商行"
    },
    {
        "id":"4lsll7yyx2u4j",
        "rate":"AA-",
        "short_name":"芜湖扬子农商行"
    },
    {
        "id":"4lssglkc6maaf",
        "rate":"A+",
        "short_name":"无为农商行"
    },
    {
        "id":"4lt0zsuiaeyag",
        "rate":"AA",
        "short_name":"友利银行(中国)"
    },
    {
        "id":"4mg013rvrrug1",
        "rate":"A+",
        "short_name":"新余农商行"
    },
    {
        "id":"4mgb67smlf0g2",
        "rate":"AA",
        "short_name":"中旅银行"
    },
    {
        "id":"4mgca1vzhd0g3",
        "rate":"A+",
        "short_name":"阳泉商行"
    },
    {
        "id":"4mgd3u7w88ag4",
        "rate":"A+",
        "short_name":"九华农商行"
    },
    {
        "id":"4mj1cc630agh5",
        "rate":"AA+",
        "short_name":"厦门农商行"
    },
    {
        "id":"4mjfsjq5ou4gc",
        "rate":"A",
        "short_name":"盂县农商行"
    },
    {
        "id":"4mjqtq3vjh6gf",
        "rate":"AA-",
        "short_name":"景德镇农商行"
    },
    {
        "id":"4mltrr0t28ugl",
        "rate":"AA",
        "short_name":"韩亚银行"
    },
    {
        "id":"4n1zktuknoi7v",
        "rate":"A+",
        "short_name":"枞阳农商行"
    },
    {
        "id":"4nwftwk130soc",
        "rate":"A-",
        "short_name":"封开农信社"
    },
    {
        "id":"4obwz537xcmjt",
        "rate":"AA+",
        "short_name":"桂林银行"
    },
    {
        "id":"4p00eg49sogh5",
        "rate":"AA-",
        "short_name":"雅安商行"
    },
    {
        "id":"4p0ieju4zgehc",
        "rate":"A+",
        "short_name":"东方农商行"
    },
    {
        "id":"4p0unvlxns0hi",
        "rate":"A-",
        "short_name":"皖江农商行"
    },
    {
        "id":"4p13sjvzp80hn",
        "rate":"AA+",
        "short_name":"企业银行(中国)"
    },
    {
        "id":"4p2q6y252smhp",
        "rate":"A+",
        "short_name":"丹东银行"
    },
    {
        "id":"4p2qvjxwm5ohq",
        "rate":"AA+",
        "short_name":"西藏银行"
    },
    {
        "id":"4p3nf7a9quahu",
        "rate":"AA-",
        "short_name":"通商农商行"
    },
    {
        "id":"4p42lefy3dihw",
        "rate":"A",
        "short_name":"高淳农商行"
    },
    {
        "id":"4p71hfwb4gui9",
        "rate":"A",
        "short_name":"阜宁农商行"
    },
    {
        "id":"4p7spyu9nxoak",
        "rate":"AA-",
        "short_name":"邹平农商行"
    },
    {
        "id":"4p7ww0ny6ugal",
        "rate":"AAA",
        "short_name":"平安银行上海分行"
    },
    {
        "id":"4psjtdz6iicav",
        "rate":"AA-",
        "short_name":"营口沿海银行"
    },
    {
        "id":"4pt7mnwh51kb0",
        "rate":"A",
        "short_name":"平潭农商行"
    },
    {
        "id":"4ptfv7b1gteb1",
        "rate":"A+",
        "short_name":"铁岭银行"
    },
    {
        "id":"4pv3nwxjkkibh",
        "rate":"A+",
        "short_name":"肥西农商行"
    },
    {
        "id":"4pv8pp7d7b2bl",
        "rate":"AAA",
        "short_name":"南洋商行"
    },
    {
        "id":"4pvycf1cycsbu",
        "rate":"A",
        "short_name":"北都农商行"
    },
    {
        "id":"4q07hcs92ywc5",
        "rate":"A+",
        "short_name":"铜陵农商行"
    },
    {
        "id":"4q1eifv47e2nv",
        "rate":"A+",
        "short_name":"睢宁农商行"
    },
    {
        "id":"4qfohmtyzryij",
        "rate":"AAA",
        "short_name":"浦发银行上海分行"
    },
    {
        "id":"4qgogli6h7gj4",
        "rate":"AAA",
        "short_name":"招行上海分行"
    },
    {
        "id":"4r3ak4mp8vgh5",
        "rate":"AA-",
        "short_name":"开平农信社"
    },
    {
        "id":"4r8ij2lyvpoas",
        "rate":"AA-",
        "short_name":"温岭农商行"
    },
    {
        "id":"4r8kzwjeq9gat",
        "rate":"A",
        "short_name":"浦江农商行"
    },
    {
        "id":"4rnrmc2atx2nc",
        "rate":"A",
        "short_name":"开化农信社"
    },
    {
        "id":"4t00mk6w33mfd",
        "rate":"A+",
        "short_name":"丰县农商行"
    },
    {
        "id":"4te8zgplb10pc",
        "rate":"AAA",
        "short_name":"厦门国际银行"
    },
    {
        "id":"4tl13r8nu4khn",
        "rate":"A+",
        "short_name":"翠屏农商行"
    },
    {
        "id":"4ttp7dkabfock",
        "rate":"AA",
        "short_name":"新会农商行"
    },
    {
        "id":"4ueo3ltg0yce7",
        "rate":"A+",
        "short_name":"临安农信社"
    },
    {
        "id":"4unzgzbyf7iai",
        "rate":"A+",
        "short_name":"楚雄农信社"
    },
    {
        "id":"4ywf1aar76wb7",
        "rate":"AA",
        "short_name":"佛山农商行"
    },
    {
        "id":"4ywhllaefgsb8",
        "rate":"AA-",
        "short_name":"沂水农商行"
    },
    {
        "id":"4yxj21l4pco9i",
        "rate":"A",
        "short_name":"太谷农商行"
    },
    {
        "id":"4zkvgv98k5oks",
        "rate":"A+",
        "short_name":"仪陇农商行"
    },
    {
        "id":"4zkxmonzw3wkt",
        "rate":"AA-",
        "short_name":"宁乡农商行"
    },
    {
        "id":"4zows6widy4lm",
        "rate":"AA-",
        "short_name":"如皋农商行"
    },
    {
        "id":"4zozynz8c68m8",
        "rate":"AA-",
        "short_name":"鄂尔多斯农商行"
    },
    {
        "id":"50a3t1gu9nm5",
        "rate":"A",
        "short_name":"镇海农商行"
    },
    {
        "id":"50d47mrij08mz",
        "rate":"AA",
        "short_name":"兴化农商行"
    },
    {
        "id":"50d69j7kxa0n2",
        "rate":"AA-",
        "short_name":"晋江农商行"
    },
    {
        "id":"50mzevs3yoo2t",
        "rate":"AA-",
        "short_name":"淮安农商行"
    },
    {
        "id":"50n1irbb1as2u",
        "rate":"A+",
        "short_name":"江苏滨海农商行"
    },
    {
        "id":"5307wh76g3wnm",
        "rate":"A+",
        "short_name":"汇川农商行"
    },
    {
        "id":"54j1naxj0b49s",
        "rate":"A+",
        "short_name":"兰陵农商行"
    },
    {
        "id":"54j966w2rg49t",
        "rate":"A",
        "short_name":"蛟河农商行"
    },
    {
        "id":"54tm6lnbcd47j",
        "rate":"AA-",
        "short_name":"颍东农商行"
    },
    {
        "id":"55lp55t1smwd7",
        "rate":"AA-",
        "short_name":"枣庄银行"
    },
    {
        "id":"55nwjv74oh9z",
        "rate":"A",
        "short_name":"惠东农商行"
    },
    {
        "id":"55qpffqs5vgdk",
        "rate":"AAA",
        "short_name":"中原银行"
    },
    {
        "id":"56avnsl63use1",
        "rate":"AA-",
        "short_name":"靖江农商行"
    },
    {
        "id":"56ke5po61doln",
        "rate":"A+",
        "short_name":"民丰农商行"
    },
    {
        "id":"56kgc72984olo",
        "rate":"AA-",
        "short_name":"平湖农商行"
    },
    {
        "id":"57x5b7is0nsa6",
        "rate":"A+",
        "short_name":"福鼎农信社"
    },
    {
        "id":"59nyzety5csb2",
        "rate":"AA+",
        "short_name":"常熟农商行"
    },
    {
        "id":"5cos2pgbut4j",
        "rate":"AA-",
        "short_name":"肥城农商行"
    },
    {
        "id":"5cqbmpxwlp4k",
        "rate":"A",
        "short_name":"上饶农商行"
    },
    {
        "id":"5crqo71b924l",
        "rate":"A",
        "short_name":"洪泽农商行"
    },
    {
        "id":"5cs0v7uprygg2",
        "rate":"A+",
        "short_name":"蒙阴农商行"
    },
    {
        "id":"5cyhoo808o4n",
        "rate":"AA-",
        "short_name":"星沙农商行"
    },
    {
        "id":"5d0lecfm9j4o",
        "rate":"A+",
        "short_name":"连江农信社"
    },
    {
        "id":"5d5x1vljsrey",
        "rate":"A",
        "short_name":"哈尔滨城郊联社"
    },
    {
        "id":"5d8db2gzg7ez",
        "rate":"AA",
        "short_name":"邯郸银行"
    },
    {
        "id":"5deh694hfz4r",
        "rate":"A-",
        "short_name":"伊金霍洛旗矿区农信社"
    },
    {
        "id":"5di3yjnu1l4t",
        "rate":"A",
        "short_name":"鹤壁农商行"
    },
    {
        "id":"5e0m5j4ys8k7h",
        "rate":"A",
        "short_name":"皖南农商行"
    },
    {
        "id":"5eq5gv3edgk5s",
        "rate":"A+",
        "short_name":"襄阳农商行"
    },
    {
        "id":"5fbv3hji2bg63",
        "rate":"A+",
        "short_name":"阆中农商行"
    },
    {
        "id":"5fiu4zbjol4qn",
        "rate":"AA+",
        "short_name":"天津农商行"
    },
    {
        "id":"5jsebffn0i8n5",
        "rate":"AA",
        "short_name":"平顶山银行"
    },
    {
        "id":"5k3r01bcclkkr",
        "rate":"A-",
        "short_name":"太仆寺农商行"
    },
    {
        "id":"5k3sqpcxlfgks",
        "rate":"A+",
        "short_name":"濉溪农商行"
    },
    {
        "id":"5kt9rq8f46saz",
        "rate":"AA-",
        "short_name":"浏阳农商行"
    },
    {
        "id":"5loi4ylqbnsdk",
        "rate":"BBB+",
        "short_name":"交城农商行"
    },
    {
        "id":"5lubmuqtm6wjb",
        "rate":"AA",
        "short_name":"鞍山银行"
    },
    {
        "id":"5lubmxi3xh0jy",
        "rate":"AA+",
        "short_name":"包商银行"
    },
    {
        "id":"5lubnd99uxclr",
        "rate":"AAA",
        "short_name":"北京银行"
    },
    {
        "id":"5lubnfcmeo0m9",
        "rate":"AAA",
        "short_name":"渤海银行"
    },
    {
        "id":"5lubnhc8tnwmq",
        "rate":"AAA",
        "short_name":"北京农商行"
    },
    {
        "id":"5lubnlf7td8np",
        "rate":"AA",
        "short_name":"沧州银行"
    },
    {
        "id":"5lubnn2dfl0o3",
        "rate":"AAA",
        "short_name":"长沙银行"
    },
    {
        "id":"5lubnqkz3zgox",
        "rate":"AAA",
        "short_name":"成都银行"
    },
    {
        "id":"5lubnu7oqhgps",
        "rate":"AA+",
        "short_name":"三峡银行"
    },
    {
        "id":"5lubnx9u5sgqh",
        "rate":"AAA",
        "short_name":"大连银行"
    },
    {
        "id":"5lubnzcucggqz",
        "rate":"AA",
        "short_name":"长城华西行"
    },
    {
        "id":"5lubo1sd9sgrk",
        "rate":"AA+",
        "short_name":"东莞银行"
    },
    {
        "id":"5lubo2d7vugrp",
        "rate":"AAA",
        "short_name":"东亚银行"
    },
    {
        "id":"5lubod9qo3c5b",
        "rate":"AA",
        "short_name":"阜新银行"
    },
    {
        "id":"5lubodm8i1w5e",
        "rate":"AA+",
        "short_name":"闽海峡银行"
    },
    {
        "id":"5lubog1rf0k5z",
        "rate":"AA",
        "short_name":"赣州银行"
    },
    {
        "id":"5lubokbd38s6z",
        "rate":"AAA",
        "short_name":"广发银行"
    },
    {
        "id":"5lubolhoido77",
        "rate":"AA+",
        "short_name":"北部湾银行"
    },
    {
        "id":"5luboosua9s80",
        "rate":"AAA",
        "short_name":"广州农商行"
    },
    {
        "id":"5luboqqru1s8h",
        "rate":"AAA",
        "short_name":"贵阳银行"
    },
    {
        "id":"5lubotcqru094",
        "rate":null,
        "short_name":"国开行"
    },
    {
        "id":"5lubp02x5osar",
        "rate":"AA+",
        "short_name":"甘肃银行"
    },
    {
        "id":"5lubp4txee0bw",
        "rate":"AAA",
        "short_name":"哈尔滨银行"
    },
    {
        "id":"5lubp6z06z8cf",
        "rate":"AA+",
        "short_name":"汉口银行"
    },
    {
        "id":"5lubp7fafdwcj",
        "rate":"AA+",
        "short_name":"杭州联合银行"
    },
    {
        "id":"5lubp8jzaakct",
        "rate":"AAA",
        "short_name":"杭州银行"
    },
    {
        "id":"5lubpb1k8pcdf",
        "rate":"AAA",
        "short_name":"河北银行"
    },
    {
        "id":"5lubpeiyzbsea",
        "rate":"AAA",
        "short_name":"恒丰银行"
    },
    {
        "id":"5lubpn47d6kgd",
        "rate":"AAA",
        "short_name":"华夏银行"
    },
    {
        "id":"5lubpph8ep8gy",
        "rate":"AAA",
        "short_name":"徽商银行"
    },
    {
        "id":"5lubq1tdgvcjz",
        "rate":"AA+",
        "short_name":"吉林银行"
    },
    {
        "id":"5lubqb5msg8m8",
        "rate":"AAA",
        "short_name":"江苏银行"
    },
    {
        "id":"5lubqe8g69gmz",
        "rate":"AAA",
        "short_name":"交行"
    },
    {
        "id":"5lubqhbko9gnq",
        "rate":"AAA",
        "short_name":"锦州银行"
    },
    {
        "id":"5lubqiko3vso1",
        "rate":"AA+",
        "short_name":"九江银行"
    },
    {
        "id":"5lubqw825xcrd",
        "rate":"AA+",
        "short_name":"兰州银行"
    },
    {
        "id":"5lubqyoljj82z",
        "rate":"AA+",
        "short_name":"辽阳银行"
    },
    {
        "id":"5lubr2hkgaw3x",
        "rate":"AA",
        "short_name":"泸州商行"
    },
    {
        "id":"5lubr35srxc43",
        "rate":"AA",
        "short_name":"乐山商行"
    },
    {
        "id":"5lubr3hvu3o46",
        "rate":"AA-",
        "short_name":"莱商银行"
    },
    {
        "id":"5lubr3xxsxg4a",
        "rate":"AA+",
        "short_name":"洛阳银行"
    },
    {
        "id":"5lubra3mr6c5s",
        "rate":"AAA",
        "short_name":"江西银行"
    },
    {
        "id":"5lubrcshq1c6g",
        "rate":"AAA",
        "short_name":"南京银行"
    },
    {
        "id":"5lubrflfha875",
        "rate":"AAA",
        "short_name":"宁波银行"
    },
    {
        "id":"5lubrigtnjg7p",
        "rate":"AA+",
        "short_name":"鄞州银行"
    },
    {
        "id":"5lubrn4s15k8l",
        "rate":"AAA",
        "short_name":"平安银行"
    },
    {
        "id":"5lubrot2fjo90",
        "rate":"AA",
        "short_name":"攀枝花商行"
    },
    {
        "id":"5lubrph5pvw96",
        "rate":"AA+",
        "short_name":"齐鲁银行"
    },
    {
        "id":"5lubrtrys24a7",
        "rate":"AAA",
        "short_name":"青岛银行"
    },
    {
        "id":"5lubru454ooaa",
        "rate":"AA",
        "short_name":"泉州银行"
    },
    {
        "id":"5lubru84zi4ab",
        "rate":"AA",
        "short_name":"齐商银行"
    },
    {
        "id":"5lubrvkh8woan",
        "rate":"AA",
        "short_name":"日照银行"
    },
    {
        "id":"5lubrw4n8j0as",
        "rate":"AAA",
        "short_name":"瑞穗银行"
    },
    {
        "id":"5lubsaupdxwec",
        "rate":"AAA",
        "short_name":"上海农商行"
    },
    {
        "id":"5lubsb2rk0cee",
        "rate":"AAA",
        "short_name":"浦发银行"
    },
    {
        "id":"5lubsdr7q64f2",
        "rate":"AAA",
        "short_name":"上海银行"
    },
    {
        "id":"5lubskwkdesgu",
        "rate":"AAA",
        "short_name":"盛京银行"
    },
    {
        "id":"5lubt1l6gj0kx",
        "rate":"AA-",
        "short_name":"石嘴山银行"
    },
    {
        "id":"5lubt7paibcmf",
        "rate":"AA+",
        "short_name":"台州银行"
    },
    {
        "id":"5lubtfyp4food",
        "rate":"AAA",
        "short_name":"天津银行"
    },
    {
        "id":"5lubtl1a17wpm",
        "rate":"AA+",
        "short_name":"天津滨海农商行"
    },
    {
        "id":"5lubtoatg3wqf",
        "rate":"AA+",
        "short_name":"温州银行"
    },
    {
        "id":"5lubts0s3g8rc",
        "rate":"AA+",
        "short_name":"武汉农商行"
    },
    {
        "id":"5lubtuxccfw30",
        "rate":"AA+",
        "short_name":"乌鲁木齐银行"
    },
    {
        "id":"5lubu03wxqk4a",
        "rate":"AA+",
        "short_name":"厦门银行"
    },
    {
        "id":"5lubu4mkq745e",
        "rate":"AAA",
        "short_name":"兴业银行"
    },
    {
        "id":"5lubu4yormc5h",
        "rate":"AAA",
        "short_name":"星展银行"
    },
    {
        "id":"5lubuiqug8o8t",
        "rate":"AA+",
        "short_name":"营口银行"
    },
    {
        "id":"5lubur2c9awat",
        "rate":"AA+",
        "short_name":"张家口商行"
    },
    {
        "id":"5luburw0h68b0",
        "rate":"AAA",
        "short_name":"招商银行"
    },
    {
        "id":"5lubuw3ybfcbz",
        "rate":"AA+",
        "short_name":"泰隆商行"
    },
    {
        "id":"5lubuxbvitcca",
        "rate":"AAA",
        "short_name":"浙商银行"
    },
    {
        "id":"5lubuyrrehwcn",
        "rate":"AAA",
        "short_name":"郑州银行"
    },
    {
        "id":"5lubv44wu50dz",
        "rate":"AAA",
        "short_name":"工商银行"
    },
    {
        "id":"5lubv4p01wke4",
        "rate":"AAA",
        "short_name":"工行上海分行"
    },
    {
        "id":"5lubv513av8e7",
        "rate":"AAA",
        "short_name":"光大银行"
    },
    {
        "id":"5lubv92m5t0f7",
        "rate":"AAA",
        "short_name":"建行"
    },
    {
        "id":"5lubvcbibeog0",
        "rate":"AAA",
        "short_name":"民生银行"
    },
    {
        "id":"5lubvdw9dnoge",
        "rate":"AAA",
        "short_name":"农业银行"
    },
    {
        "id":"5lubvfzpu5ogt",
        "rate":null,
        "short_name":"农行上海分行"
    },
    {
        "id":"5lubvldgeu4i5",
        "rate":"AAA",
        "short_name":"中行"
    },
    {
        "id":"5lubvlxqc6sia",
        "rate":"AAA",
        "short_name":"中行上海分行"
    },
    {
        "id":"5lubvsk6v5ojx",
        "rate":"AAA",
        "short_name":"中信银行"
    },
    {
        "id":"5lubvw6vi94kt",
        "rate":"AAA",
        "short_name":"重庆农商行"
    },
    {
        "id":"5lubvzqamm4lm",
        "rate":"AAA",
        "short_name":"重庆银行"
    },
    {
        "id":"5lubw7j6nzwnj",
        "rate":"AA+",
        "short_name":"民泰商行"
    },
    {
        "id":"5lubwaxmtrso2",
        "rate":"AAA",
        "short_name":"渣打银行(中国)"
    },
    {
        "id":"5lubwgovx94p1",
        "rate":"AA",
        "short_name":"余杭农商行"
    },
    {
        "id":"5lubwndirugqm",
        "rate":"AAA",
        "short_name":"中信银行上海分行"
    },
    {
        "id":"5m49t570mewne",
        "rate":"A+",
        "short_name":"盘龙农信社"
    },
    {
        "id":"5mhyh142otgpw",
        "rate":"AAA",
        "short_name":"建行上海分行"
    },
    {
        "id":"5n3zfpahlvg8t",
        "rate":"AAA",
        "short_name":"三井住友银行"
    },
    {
        "id":"5ne9jbepk88ih",
        "rate":"AA",
        "short_name":"朝阳银行"
    },
    {
        "id":"5oo93blva8o6y",
        "rate":"A+",
        "short_name":"炎陵农商行"
    },
    {
        "id":"5piyomc6do4mv",
        "rate":"A+",
        "short_name":"四会农商行"
    },
    {
        "id":"5s3580wpoy4lm",
        "rate":"A+",
        "short_name":"赣昌农商行"
    },
    {
        "id":"5s37df5ywckln",
        "rate":"A-",
        "short_name":"龙泉农信社"
    },
    {
        "id":"5tbpyvtnp3488",
        "rate":"A+",
        "short_name":"镇江农商行"
    },
    {
        "id":"5uxkpgrf5joga",
        "rate":"A-",
        "short_name":"威远农商行"
    },
    {
        "id":"5y7hg2ymccccn",
        "rate":"AA+",
        "short_name":"龙江银行"
    },
    {
        "id":"5zsbtpjnfu50",
        "rate":"A+",
        "short_name":"宜春农商行"
    },
    {
        "id":"60nws1drfgw32",
        "rate":"A+",
        "short_name":"宁海农商行"
    },
    {
        "id":"60o2n0ne5bs33",
        "rate":"AA-",
        "short_name":"伊金霍洛农商行"
    },
    {
        "id":"61itfg5ihb0au",
        "rate":"A+",
        "short_name":"阿拉善农商行"
    },
    {
        "id":"631utor8jr3h",
        "rate":"A+",
        "short_name":"巨野农商行"
    },
    {
        "id":"6347fhra9f3i",
        "rate":"AA-",
        "short_name":"湘江新区农商行"
    },
    {
        "id":"63dyzqc1j3w5d",
        "rate":"AAA",
        "short_name":"永亨银行"
    },
    {
        "id":"64eucerwq2w5i",
        "rate":"A+",
        "short_name":"龙海农商行"
    },
    {
        "id":"64evyj5wywo5j",
        "rate":"A+",
        "short_name":"博山农商行"
    },
    {
        "id":"66b0pyfpspba",
        "rate":"A+",
        "short_name":"乳山农商行"
    },
    {
        "id":"66cdf0h6m8b4",
        "rate":"AA+",
        "short_name":"贵州银行"
    },
    {
        "id":"66q46vatihax",
        "rate":"AA+",
        "short_name":"萧山农商行"
    },
    {
        "id":"68mize3wqpgbg",
        "rate":"A",
        "short_name":"青阳农商行"
    },
    {
        "id":"68vco1spuacc5",
        "rate":"A+",
        "short_name":"淄川农商行"
    },
    {
        "id":"69l4i9asfrcd",
        "rate":"AA",
        "short_name":"上饶银行"
    },
    {
        "id":"69m0zrvcqlgq",
        "rate":"A+",
        "short_name":"江山农商行"
    },
    {
        "id":"6a8bsint7ngqd",
        "rate":"AAA",
        "short_name":"华夏银行上海自贸分行"
    },
    {
        "id":"6enepr8y4q0mn",
        "rate":"A",
        "short_name":"大埔农商行"
    },
    {
        "id":"6f98g1rgai8q7",
        "rate":"A+",
        "short_name":"吴兴农商行"
    },
    {
        "id":"6fc15lvd6kgq9",
        "rate":"AA",
        "short_name":"南通农商行"
    },
    {
        "id":"6h52zprenskqy",
        "rate":"A-",
        "short_name":"左权农商行"
    },
    {
        "id":"6p9zluvye9kij",
        "rate":"A2",
        "short_name":"恒生中国上海分行"
    },
    {
        "id":"6piqy1z8bbops",
        "rate":"A",
        "short_name":"万安农商行"
    },
    {
        "id":"6pnzqnzrkl49j",
        "rate":"A+",
        "short_name":"嘉祥农商行"
    },
    {
        "id":"6po34f2qh1o9k",
        "rate":"BBB",
        "short_name":"恒升村镇行"
    },
    {
        "id":"6pvo3yvswko9w",
        "rate":"BBB+",
        "short_name":"诸暨村镇行"
    },
    {
        "id":"6umz3ohlepshc",
        "rate":"A",
        "short_name":"广德农商行"
    },
    {
        "id":"6v8u40ers64k8",
        "rate":"A+",
        "short_name":"庐江农商行"
    },
    {
        "id":"6vlv3o7aqaf2",
        "rate":"A",
        "short_name":"宾州农商行"
    },
    {
        "id":"6vudpkpbb6o5a",
        "rate":"A+",
        "short_name":"安岳农信社"
    },
    {
        "id":"6wm3n8mv50ka4",
        "rate":"A+",
        "short_name":"遂溪农信社"
    },
    {
        "id":"6wm4zl42t0ca5",
        "rate":"A",
        "short_name":"广宁农信社"
    },
    {
        "id":"6x2bdkxjvwoiw",
        "rate":"A+",
        "short_name":"榆次农商行"
    },
    {
        "id":"6xhlirybqd84",
        "rate":"A+",
        "short_name":"孝义农商行"
    },
    {
        "id":"6z2zvwlolvgaf",
        "rate":"A+",
        "short_name":"五莲农商行"
    },
    {
        "id":"723x8op9ep4ri",
        "rate":"A+",
        "short_name":"许都农商行"
    },
    {
        "id":"7491fxfvupq7",
        "rate":"AA-",
        "short_name":"晋中银行"
    },
    {
        "id":"757su0o4naoj2",
        "rate":"A",
        "short_name":"霍山农商行"
    },
    {
        "id":"76a10g2z2so90",
        "rate":"AA-",
        "short_name":"喀什农商行"
    },
    {
        "id":"76a2wqiolro91",
        "rate":"A",
        "short_name":"聊城润昌农商行"
    },
    {
        "id":"76ki68wvoa4dk",
        "rate":"A+",
        "short_name":"莘县农商行"
    },
    {
        "id":"7898jyrrt98pq",
        "rate":"A+",
        "short_name":"仙游农信社"
    },
    {
        "id":"78m4eu5elzw7n",
        "rate":"A",
        "short_name":"利津农商行"
    },
    {
        "id":"7a8cd36m9j0fc",
        "rate":"A+",
        "short_name":"张家界农商行"
    },
    {
        "id":"7b7fw2eu76waz",
        "rate":"A",
        "short_name":"五常农商行"
    },
    {
        "id":"7b7hfzn2u04b0",
        "rate":"BBB",
        "short_name":"邗江村镇行"
    },
    {
        "id":"7c87ablp3e8j2",
        "rate":"AAA",
        "short_name":"北京银行上海分行"
    },
    {
        "id":"7c9dk7g168sj7",
        "rate":"AA-",
        "short_name":"聊城农商行"
    },
    {
        "id":"7d2n91mut204i",
        "rate":"A",
        "short_name":"兴义农商行"
    },
    {
        "id":"7d2p4zr7c0g4j",
        "rate":"A+",
        "short_name":"舒城农商行"
    },
    {
        "id":"7ddk14be0sobf",
        "rate":"AA-",
        "short_name":"大庆农商行"
    },
    {
        "id":"7eg1j60fqicni",
        "rate":"A",
        "short_name":"壶关农商行"
    },
    {
        "id":"7jnr94d1094qa",
        "rate":"A",
        "short_name":"彝族农信社"
    },
    {
        "id":"7qib472j94ne",
        "rate":"AA-",
        "short_name":"枣庄农商行"
    },
    {
        "id":"7rbdmwryowkc7",
        "rate":"A+",
        "short_name":"新密农商行"
    },
    {
        "id":"7s2gyouladkdg",
        "rate":"A",
        "short_name":"山阴农商行"
    },
    {
        "id":"7w999e05of5",
        "rate":"A+",
        "short_name":"东平农商行"
    },
    {
        "id":"8bwmogxvsy36",
        "rate":"A+",
        "short_name":"端州农商行"
    },
    {
        "id":"8byeu0rv5s39",
        "rate":"AA",
        "short_name":"济宁银行"
    },
    {
        "id":"8p8bmzbd9a3b",
        "rate":"AA",
        "short_name":"南昌农商行"
    },
    {
        "id":"8qpk8x6n1tod",
        "rate":"A+",
        "short_name":"广饶农商行"
    },
    {
        "id":"90bv9062t34f",
        "rate":"AA-",
        "short_name":"南安农商行"
    },
    {
        "id":"9h1a2581h8dr",
        "rate":"AA-",
        "short_name":"瓯海农商行"
    },
    {
        "id":"9hv91kq626qa",
        "rate":"A+",
        "short_name":"宝生村镇行"
    },
    {
        "id":"9hwtduqdt5qb",
        "rate":"A+",
        "short_name":"弥勒农商行"
    },
    {
        "id":"9ptjducn4ifc",
        "rate":"A+",
        "short_name":"清徐农商行"
    },
    {
        "id":"9puuko7kidfd",
        "rate":"A-",
        "short_name":"芮城农商行"
    },
    {
        "id":"a44a853hgqn0",
        "rate":"A+",
        "short_name":"句容农商行"
    },
    {
        "id":"a46twbmlsan1",
        "rate":"A+",
        "short_name":"盱眙农商行"
    },
    {
        "id":"a49fcc9z4wn2",
        "rate":"A",
        "short_name":"建德农商行"
    },
    {
        "id":"a4bl3ach3wn3",
        "rate":"A+",
        "short_name":"普陀农商行"
    },
    {
        "id":"a4dzb52djvn7",
        "rate":"A",
        "short_name":"仙居农信社"
    },
    {
        "id":"a4frxpmfqrn8",
        "rate":"A",
        "short_name":"扬中农商行"
    },
    {
        "id":"a8swviztnlc7",
        "rate":"A+",
        "short_name":"确山农商行"
    },
    {
        "id":"a8zsddqar1c8",
        "rate":"A-",
        "short_name":"东盈村镇行"
    },
    {
        "id":"a928n9fuagc9",
        "rate":"A-",
        "short_name":"临淄农商行"
    },
    {
        "id":"a96cnw8x1nd0",
        "rate":"A+",
        "short_name":"泽州农商行"
    },
    {
        "id":"a97rdgg3t6d1",
        "rate":"A",
        "short_name":"沂源农商行"
    },
    {
        "id":"a9e75ha9o5d2",
        "rate":"A+",
        "short_name":"偃师农商行"
    },
    {
        "id":"aj03epqervrm",
        "rate":"A",
        "short_name":"伊犁农商行"
    },
    {
        "id":"aj1zk84xwnrn",
        "rate":"A-",
        "short_name":"响水农商行"
    },
    {
        "id":"b2z066ihqjdd",
        "rate":"AA",
        "short_name":"潍坊银行"
    },
    {
        "id":"b356kgp9sw5k",
        "rate":"AAA",
        "short_name":"广州银行"
    },
    {
        "id":"b4w3f2e9bh5s",
        "rate":"AA+",
        "short_name":"南粤银行"
    },
    {
        "id":"bdhjww15xah8",
        "rate":"AA-",
        "short_name":"中牟农商行"
    },
    {
        "id":"bk4ju6nnylh9",
        "rate":"A-",
        "short_name":"洞头农信社"
    },
    {
        "id":"c2t5hqkc3yk2",
        "rate":"AA-",
        "short_name":"凉山农商行"
    },
    {
        "id":"c6gw2kktv6ne",
        "rate":"A+",
        "short_name":"汝州农商行"
    },
    {
        "id":"c805cl3wosnf",
        "rate":"A+",
        "short_name":"沂南农商行"
    },
    {
        "id":"cte74h207gnp",
        "rate":"A+",
        "short_name":"平邑农商行"
    },
    {
        "id":"cxkbqcbkv5no",
        "rate":"A+",
        "short_name":"信宜农商行"
    },
    {
        "id":"d11h9dipzj5s",
        "rate":"A+",
        "short_name":"正定农商行"
    },
    {
        "id":"d132146xh15t",
        "rate":"A+",
        "short_name":"桓台农商行"
    },
    {
        "id":"d33vxa0hia5w",
        "rate":"AA-",
        "short_name":"新泰农商行"
    },
    {
        "id":"dnx2snjv6dp0",
        "rate":"AA-",
        "short_name":"三水农信社"
    },
    {
        "id":"dny36k1fd6jd",
        "rate":"A+",
        "short_name":"河东农商行"
    },
    {
        "id":"dnylsli3t8p1",
        "rate":"A",
        "short_name":"东明农商行"
    },
    {
        "id":"dnziknfq28je",
        "rate":"AA",
        "short_name":"网商银行"
    },
    {
        "id":"do06bx8ze9p2",
        "rate":"A+",
        "short_name":"瓮安农商行"
    },
    {
        "id":"do2o79c2lrp3",
        "rate":"A+",
        "short_name":"海口联合农商行"
    },
    {
        "id":"dtctn38nxtep",
        "rate":"AA",
        "short_name":"黄河农商行"
    },
    {
        "id":"ejhk5f1t70d4",
        "rate":"AA",
        "short_name":"海口农商行"
    },
    {
        "id":"f8m4r5t7g49d",
        "rate":"A+",
        "short_name":"寿阳农商行"
    },
    {
        "id":"f8nzf8ism99e",
        "rate":"A+",
        "short_name":"平遥农商行"
    },
    {
        "id":"fanrxwjtpnpv",
        "rate":"AA",
        "short_name":"金华银行"
    },
    {
        "id":"fcc5rb1715pg",
        "rate":"AA+",
        "short_name":"四川天府银行"
    },
    {
        "id":"fgwbk4f1mn9e",
        "rate":"A-",
        "short_name":"庆元农信社"
    },
    {
        "id":"fkb8qnh3yblw",
        "rate":"A+",
        "short_name":"河套农商行"
    },
    {
        "id":"fmd9om7wbkm5",
        "rate":"A",
        "short_name":"辉县农商行"
    },
    {
        "id":"g32j99m6u27z",
        "rate":"AA+",
        "short_name":"内蒙古银行"
    },
    {
        "id":"g6pforro2ere",
        "rate":"AA",
        "short_name":"大连农商行"
    },
    {
        "id":"g7dwq9pd1pmx",
        "rate":"AA-",
        "short_name":"张店农商行"
    },
    {
        "id":"g7xfsk533yqu",
        "rate":null,
        "short_name":"新昌浦发村镇银行"
    },
    {
        "id":"guqdaov8fbl7",
        "rate":"AA-",
        "short_name":"射阳农商行"
    },
    {
        "id":"h2gwmrvug7l7",
        "rate":"AA+",
        "short_name":"前海微众银行"
    },
    {
        "id":"h7m43hpsdyau",
        "rate":"A+",
        "short_name":"宝丰农商行"
    },
    {
        "id":"hb4d9xzp7zbf",
        "rate":"A",
        "short_name":"湖滨农商行"
    },
    {
        "id":"hit5ln0w55lz",
        "rate":"AA+",
        "short_name":"紫金农商行"
    },
    {
        "id":"hiv81ccf0hm0",
        "rate":"A+",
        "short_name":"淳安农商行"
    },
    {
        "id":"i1uoty98pqrd",
        "rate":"AA-",
        "short_name":"雅安农商行"
    },
    {
        "id":"j06ob81dr4h5",
        "rate":"A",
        "short_name":"临清农商行"
    },
    {
        "id":"j1g1ajufxrh7",
        "rate":"A2",
        "short_name":"恒生银行"
    },
    {
        "id":"j1hivs91neh8",
        "rate":"A+",
        "short_name":"正阳农商行"
    },
    {
        "id":"jr43qeapqd57",
        "rate":"AA+",
        "short_name":"青岛农商行"
    },
    {
        "id":"kb1zypgizhoz",
        "rate":"AA-",
        "short_name":"如东农商行"
    },
    {
        "id":"khfibz8gdi4o",
        "rate":"AA+",
        "short_name":"瑞丰银行"
    },
    {
        "id":"kpc3huxr3cgk",
        "rate":"AA",
        "short_name":"慈溪农商行"
    },
    {
        "id":"kpecuf0dzxgl",
        "rate":"AA+",
        "short_name":"中山农商行"
    },
    {
        "id":"l6gqzs9pr3kt",
        "rate":"A-",
        "short_name":"陕坝农商行"
    },
    {
        "id":"l6igqknj7vku",
        "rate":"AA-",
        "short_name":"台山农信社"
    },
    {
        "id":"lb2i3w95rzfu",
        "rate":"A",
        "short_name":"蓬莱农商行"
    },
    {
        "id":"lb3rptz7w1fv",
        "rate":"BBB-",
        "short_name":"长岛农商行"
    },
    {
        "id":"lb6fu6n8u2gj",
        "rate":"A",
        "short_name":"海阳农商行"
    },
    {
        "id":"lb7qe1phmlgk",
        "rate":"A",
        "short_name":"莱阳农商行"
    },
    {
        "id":"lb8wh03u0qgl",
        "rate":"A",
        "short_name":"招远农商行"
    },
    {
        "id":"le40jxvx2cb9",
        "rate":"AA-",
        "short_name":"海门农商行"
    },
    {
        "id":"lsw4rtkwxrkm",
        "rate":"AA",
        "short_name":"启东农商行"
    },
    {
        "id":"lsyfy6e46pkn",
        "rate":"AA-",
        "short_name":"嘉善农商行"
    },
    {
        "id":"lt06tfwgstko",
        "rate":"A+",
        "short_name":"东海农商行"
    },
    {
        "id":"m64kbazpst3n",
        "rate":"A+",
        "short_name":"章丘农商行"
    },
    {
        "id":"m65jny545z3o",
        "rate":"A",
        "short_name":"栖霞农商行"
    },
    {
        "id":"mawgxfbrbr2s",
        "rate":"A+",
        "short_name":"安阳商都农商行"
    },
    {
        "id":"mayac6h3n62t",
        "rate":"A",
        "short_name":"贺兰农商行"
    },
    {
        "id":"mbmm9t7j8ba2",
        "rate":"AA",
        "short_name":"绵阳商行"
    },
    {
        "id":"muye1f991451",
        "rate":"A+",
        "short_name":"大通农商行"
    },
    {
        "id":"n9xtm5h2dpj6",
        "rate":"A",
        "short_name":"乌拉特农商行"
    },
    {
        "id":"na2u1bdr98j7",
        "rate":"A",
        "short_name":"三门银座村镇行"
    },
    {
        "id":"nx12b9qmwdp1",
        "rate":"AA-",
        "short_name":"马鞍山农商行"
    },
    {
        "id":"nxzimrigtqji",
        "rate":"A",
        "short_name":"丹阳农商行"
    },
    {
        "id":"ol02o114ibh7",
        "rate":"AAA",
        "short_name":"华融湘江银行"
    },
    {
        "id":"olxqqukqzhi9",
        "rate":"AAA",
        "short_name":"巴黎银行"
    },
    {
        "id":"omhjrsrr1aia",
        "rate":"A+",
        "short_name":"曲靖商行"
    },
    {
        "id":"opb5j641065s",
        "rate":"A",
        "short_name":"中卫农商行"
    },
    {
        "id":"piw6a77ro6om",
        "rate":"AAA",
        "short_name":"成都农商行"
    },
    {
        "id":"pjws42i1n233",
        "rate":"A",
        "short_name":"宜阳农商行"
    },
    {
        "id":"q1ikvwn9csqx",
        "rate":"A+",
        "short_name":"兰溪农商行"
    },
    {
        "id":"q1m48bft6gqy",
        "rate":"AA-",
        "short_name":"泰兴农商行"
    },
    {
        "id":"q1pco6phbmqz",
        "rate":"AA",
        "short_name":"科技农商行"
    },
    {
        "id":"qf4g57xuyb3t",
        "rate":"AA+",
        "short_name":"富滇银行"
    },
    {
        "id":"qlnjs6tptif0",
        "rate":"AA+",
        "short_name":"晋商银行"
    },
    {
        "id":"qn5p5dnymrih",
        "rate":"AA",
        "short_name":"东营银行"
    },
    {
        "id":"qna3jzxw2raz",
        "rate":"AA-",
        "short_name":"莒南农商行"
    },
    {
        "id":"qq6aelauneb0",
        "rate":"AA-",
        "short_name":"郑州农信社"
    },
    {
        "id":"qzsmdtom7rkp",
        "rate":"AA-",
        "short_name":"江都农商行"
    },
    {
        "id":"qzv279d235kq",
        "rate":"A+",
        "short_name":"潞州农商行"
    },
    {
        "id":"r85h5aqmedr8",
        "rate":"AA",
        "short_name":"鹿城农商行"
    },
    {
        "id":"r9g5wxrwl8rb",
        "rate":"AA+",
        "short_name":"长安银行"
    },
    {
        "id":"rc2bu4yyz3cq",
        "rate":"AA",
        "short_name":"乐清农商行"
    },
    {
        "id":"rcksowjznimf",
        "rate":"A+",
        "short_name":"遂宁农商行"
    },
    {
        "id":"ri471i5zioni",
        "rate":"A",
        "short_name":"临沭农商行"
    },
    {
        "id":"s0pg801q67gq",
        "rate":"AA-",
        "short_name":"邢台银行"
    },
    {
        "id":"s0r5px1o3pgr",
        "rate":"AA-",
        "short_name":"扬州农商行"
    },
    {
        "id":"s0szj1d91pgs",
        "rate":"A",
        "short_name":"莲都农商行"
    },
    {
        "id":"s5egeoyjv34q",
        "rate":"AA",
        "short_name":"辽阳农商行"
    },
    {
        "id":"s7509m03lj4p",
        "rate":"A",
        "short_name":"同心农商行"
    },
    {
        "id":"s76fwf14xi4q",
        "rate":"AA-",
        "short_name":"辽东农商行"
    },
    {
        "id":"s79ev3w3jf4r",
        "rate":"A",
        "short_name":"固原农商行"
    },
    {
        "id":"t4qzy6e31xgh",
        "rate":"AA+",
        "short_name":"西安银行"
    },
    {
        "id":"t91rtm226630",
        "rate":"A",
        "short_name":"夏县农商行"
    },
    {
        "id":"t94803fbzy31",
        "rate":"BBB",
        "short_name":"永兴村镇行"
    },
    {
        "id":"t95qs2w5t332",
        "rate":"A+",
        "short_name":"晋城农商行"
    },
    {
        "id":"th3ghm8p9m7s",
        "rate":"A+",
        "short_name":"长乐农商行"
    },
    {
        "id":"tu9nd6vbg1ia",
        "rate":"AA-",
        "short_name":"药都农商行"
    },
    {
        "id":"tua1500gx57h",
        "rate":"AA",
        "short_name":"柳州银行"
    },
    {
        "id":"u3o3jgm7du8s",
        "rate":"AA+",
        "short_name":"华商银行"
    },
    {
        "id":"umtrt828pz42",
        "rate":"A+",
        "short_name":"达州农商行"
    },
    {
        "id":"umvxatjo5643",
        "rate":"A",
        "short_name":"东阿农商行"
    },
    {
        "id":"umxc2fyd3744",
        "rate":"A",
        "short_name":"高唐农商行"
    },
    {
        "id":"unzw3nr6fqe9",
        "rate":"AA-",
        "short_name":"漳州农商行"
    },
    {
        "id":"upmfoejgptk8",
        "rate":"A+",
        "short_name":"佛冈农信社"
    },
    {
        "id":"upoktslzwnk9",
        "rate":"AA-",
        "short_name":"十堰农商行"
    },
    {
        "id":"uxxwowpk96f5",
        "rate":"A",
        "short_name":"彭城农商行"
    },
    {
        "id":"uxzzgissv1f6",
        "rate":"A+",
        "short_name":"罗庄农商行"
    },
    {
        "id":"uy1wgd1rzyf7",
        "rate":"A+",
        "short_name":"鹿城村镇行"
    },
    {
        "id":"vlkwxwu3ltl9",
        "rate":"A+",
        "short_name":"岚山农商行"
    },
    {
        "id":"vmew8hi5qthv",
        "rate":"A+",
        "short_name":"营山农商行"
    },
    {
        "id":"vmh2dw92xohw",
        "rate":"A-",
        "short_name":"天元农信社"
    },
    {
        "id":"vmikavu13jhx",
        "rate":"A+",
        "short_name":"高要农商行"
    },
    {
        "id":"vrk70xzagfm",
        "rate":"A+",
        "short_name":"抚州农商行"
    },
    {
        "id":"vvxg9js9ufn",
        "rate":"AA-",
        "short_name":"岱岳农商行"
    },
    {
        "id":"vyvikh4j7fp",
        "rate":"A+",
        "short_name":"泰山农商行"
    },
    {
        "id":"w0c2pgnizfq",
        "rate":"A+",
        "short_name":"湘潭农商行"
    },
    {
        "id":"wjz0cupdadbc",
        "rate":"AA+",
        "short_name":"深圳农商行"
    },
    {
        "id":"wvq04vwz65t",
        "rate":"AA",
        "short_name":"瑞安农商行"
    },
    {
        "id":"wzftvuhqfaav",
        "rate":"AA",
        "short_name":"烟台银行"
    },
    {
        "id":"x0ygxgazcgn",
        "rate":"AA",
        "short_name":"尧都农商行"
    },
    {
        "id":"x40q1mup4ve7",
        "rate":"AAA",
        "short_name":"花旗银行"
    },
    {
        "id":"xfawqubtwy4q",
        "rate":"AA",
        "short_name":"禾城农商行"
    },
    {
        "id":"xiymyfp8qhmy",
        "rate":"A+",
        "short_name":"漳泽农商行"
    },
    {
        "id":"xljm1olmg3i",
        "rate":"A",
        "short_name":"稷山农商行"
    },
    {
        "id":"xocwu8quz3j",
        "rate":"AA",
        "short_name":"惠州农商行"
    },
    {
        "id":"xum8dvd7ng8m",
        "rate":"AA",
        "short_name":"盐城农商行"
    },
    {
        "id":"xyjgzcivmi7",
        "rate":"A",
        "short_name":"宁德农商行"
    },
    {
        "id":"y3r09znt5j3l",
        "rate":"A+",
        "short_name":"六安农商行"
    },
    {
        "id":"y4lziyluu1fg",
        "rate":"AA+",
        "short_name":"富邦华一银行"
    },
    {
        "id":"y4ov3m5k1s61",
        "rate":"AA+",
        "short_name":"湖北银行"
    },
    {
        "id":"y4uu8ujvro4f",
        "rate":"A",
        "short_name":"祁门农商行"
    },
    {
        "id":"ya50eivw1ec0",
        "rate":"AA-",
        "short_name":"桐庐农商行"
    },
    {
        "id":"ycl4ylhqh3e0",
        "rate":"A-",
        "short_name":"新华农信社"
    },
    {
        "id":"yjimvqko72b3",
        "rate":"AA-",
        "short_name":"石狮农商行"
    },
    {
        "id":"yjlvs6kmx4b4",
        "rate":"AA-",
        "short_name":"泗阳农商行"
    },
    {
        "id":"ywiy09gbba3g",
        "rate":"AA-",
        "short_name":"昌邑农商行"
    },
    {
        "id":"yydh6h9x9fet",
        "rate":"A",
        "short_name":"昆明市联社"
    },
    {
        "id":"yyhh9rcek0eu",
        "rate":"A",
        "short_name":"台前农商行"
    },
    {
        "id":"zb6b8rnf94v",
        "rate":"A+",
        "short_name":"三台农商行"
    },
    {
        "id":"zdjm7wgtf4w",
        "rate":"A+",
        "short_name":"遂平农商行"
    },
    {
        "id":"zdz5p3osxg57",
        "rate":"AA-",
        "short_name":"博罗农商行"
    },
    {
        "id":"ze3wevjfl958",
        "rate":"A",
        "short_name":"五华区农信社"
    },
    {
        "id":"zk37idi1ojgf",
        "rate":"AA+",
        "short_name":"中德银行"
    },
    {
        "id":"zkcknw2xrmgj",
        "rate":"A+",
        "short_name":"吉安农商行"
    },
    {
        "id":"zkxix0gupggn",
        "rate":"A+",
        "short_name":"惠安农信社"
    },
    {
        "id":"zod1ru8i7nhf",
        "rate":"A+",
        "short_name":"仪征农商行"
    },
    {
        "id":"zoem3bg4n8hg",
        "rate":"A+",
        "short_name":"北仑农信社"
    },
    {
        "id":"zoh4utz8n2hh",
        "rate":"A+",
        "short_name":"蚌埠农商行"
    },
    {
        "id":"zrh9l06dbaau",
        "rate":"A+",
        "short_name":"黎都农商行"
    },
    {
        "id":"zu8fs07fji38",
        "rate":"A-",
        "short_name":"德庆农信社"
    }
]

function make_one(_issueDeptId) {
    let pub ={
        "id":make_id(),
        "offerId":make_offerId(),
        "issueDeptId": make_issueDeptId(_issueDeptId),
        "goodsLevel":make_goodsLevel(_issueDeptId),
        "issueDay":make_issueDay(),
        // "terminal": make_terminal(),
        "terminal":'1',
        "issuePrice":make_issuePrice(),
        "issuePriceFlag":make_issuePriceFlag(),
        "planedIssueAmount":make_planedIssueAmount(),
        // "remark":make_remark(),
        "remark":'非银',
        "goodStatus":'0',
        // "goodStatus":make_goodStatus(),
        // "status":make_status(),
        "status":'1',
        "createTime":make_createTime(),
        "modifyTime":make_modifyTime(),
        "enterpriseType":make_enterpriseType(),
        "issueDate":make_issueDate(),
        "description":make_description(),
        "priceChange":make_priceChange(),
        "actualIssueAmount":make_actualIssueAmount(),
        "brokerId":make_brokerId(),
        "brokerName":make_brokerName(),
        "flagVip":make_flagVip(),
        "priceType":make_priceType()

    }

    function make_id(){
        let idStr = Date.now()
        return idStr

    }
    function make_offerId(){
        let first = Number(Math.random().toString().substr(3,3) + Date.now()).toString(36)
        let second = Number(Math.random().toString().substr(3,3) + Date.now()).toString(36)
        return first+second
    }
    function make_issueDeptId(_issueDeptId){
        return _issueDeptId
    }
    function make_goodsLevel(_issueDeptId){

        for (let i =0;i<bankinfo.length-1;i++){

            if (bankinfo[i].id === _issueDeptId){
                return bankinfo[i].rate
            }
        }

    }
    function make_issueDay(){
        return "周一"
    }
    function make_terminal(){
        return Math.floor(Math.random()*5+1).toString()
    }
    function make_issuePrice(){
        return (Math.random()*5).toFixed(2).toString()
    }
    function make_issuePriceFlag(){

        if(Math.random()>0.95){

            return '1'
        }
        else {

            return '0'
        }

    }
    function make_planedIssueAmount(){
        return Math.floor(Math.random()*100+1).toString()
    }
    function make_remark(){
        return Math.random()>0.6?'有备注':''
    }
    function make_goodStatus(){
        return '0'
    }
    function make_status(){
        return '1'
    }
    function make_createTime(){
        let date =moment().format('MM DD YYYY HH:mm')
        date+= parseInt(moment().format('HH'))<=12? 'AM':'PM'
        return date

    }
    function make_modifyTime(){
        let date =moment().format('MM DD YYYY HH:mm')
        date+= parseInt(moment().format('HH'))<=12? 'AM':'PM'
        return date
    }
    function make_enterpriseType(){
        return 'MCB'
    }
    function make_issueDate(){

        if(moment().day()<5){
            return moment().add(1,'days').format('YYYY.MM.DD')
        }else if (moment().day()===5){
            return moment().add(3,'days').format('YYYY.MM.DD')
        }

    }
    function make_description(){
        return null
    }
    function make_priceChange(){
        return Math.floor(Math.random()*15+1)*(Math.random()>0.5?1:-1).toString()
    }
    function make_actualIssueAmount(){
        return null
    }
    function make_brokerId(){
        // return Math.floor(Math.random()*4+1).toString()
        return '4'
    }
    function make_brokerName(){
        return "PATR"
    }
    function make_flagVip(){
        return null
    }
    function make_priceType(){
        return  '1'
    }


    return pub
}

var id='5lubrvkh8woan'

var one = make_one(id)

console.log(JSON.stringify(one,null,4))